layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

#collections:
 # - external_feed

collections:
  - medium_posts
  - external_feed

topics:
  - name: Medium (emirhangul)
    web_url: https://medium.com/@emirhangul
    image_url: https://pbs.twimg.com/profile_images/900033008685666305/c6Q38U35_400x400.png

  - name: LinkedIn (emirhangl0101)
    web_url: https://www.linkedin.com/in/emirhangl0101/
    image_url: https://www.atec.com.tr/wp-content/uploads/2018/05/linkedin-300x300.png

  - name: SW Test Academy 
    web_url: https://www.swtestacademy.com/author/emirhangul/
    image_url: https://avatars2.githubusercontent.com/u/13996767?s=460&v=4
